// tslint:disable:no-expression-statement
import { test } from 'ava'
import dataFetcher from './data-fetcher'

const sample = {"id":1,"created_at":"2005-05-23T23:35:31.000-04:00","uploader_id":1,"score":151,"source":"http://www.biwa.ne.jp/~kyogoku/nekotama.jpg","md5":"d34e4cf0a437a5d65f8e82b7bcd02606","last_comment_bumped_at":"2017-09-23T01:17:10.410-04:00","rating":"s","image_width":459,"image_height":650,"tag_string":"1girl ;\u003c ;p animal_ears aqua_panties bad_id bangs blue_bow blue_ribbon blush bow bow_panties breasts brown_eyes cat_ears cat_girl cat_tail collarbone colored_stripes cowboy_shot eyebrows eyebrows_visible_through_hair hands_up horizontal_stripes kemonomimi_mode kousaka_tamaki kyougoku_shin large_breasts long_hair long_sleeves looking_at_viewer no_pants one_eye_closed orange_background outside_border panties parted_bangs pink_shirt red_hair ribbon school_uniform serafuku shirt smile solo standing striped striped_background striped_panties tail thigh_gap thighhighs thighs to_heart_2 tongue tongue_out underwear very_long_hair white_legwear","is_note_locked":false,"fav_count":355,"file_ext":"jpg","last_noted_at":null,"is_rating_locked":false,"parent_id":57501,"has_children":false,"approver_id":null,"tag_count_general":55,"tag_count_artist":1,"tag_count_character":1,"tag_count_copyright":1,"file_size":127238,"is_status_locked":false,"pool_string":"pool:4068 pool:6643 pool:6762 pool:collection","up_score":135,"down_score":0,"is_pending":false,"is_flagged":false,"is_deleted":false,"tag_count":59,"updated_at":"2018-06-29T07:31:07.419-04:00","is_banned":false,"pixiv_id":null,"last_commented_at":"2018-05-01T14:03:37.208-04:00","has_active_children":false,"bit_flags":2,"tag_count_meta":1,"keeper_data":{"uid":32756},"uploader_name":"albert","has_large":false,"has_visible_children":false,"children_ids":null,"is_favorited":false,"tag_string_general":"1girl ;\u003c ;p animal_ears aqua_panties bangs blue_bow blue_ribbon blush bow bow_panties breasts brown_eyes cat_ears cat_girl cat_tail collarbone colored_stripes cowboy_shot eyebrows eyebrows_visible_through_hair hands_up horizontal_stripes kemonomimi_mode large_breasts long_hair long_sleeves looking_at_viewer no_pants one_eye_closed orange_background outside_border panties parted_bangs pink_shirt red_hair ribbon school_uniform serafuku shirt smile solo standing striped striped_background striped_panties tail thigh_gap thighhighs thighs tongue tongue_out underwear very_long_hair white_legwear","tag_string_character":"kousaka_tamaki","tag_string_copyright":"to_heart_2","tag_string_artist":"kyougoku_shin","tag_string_meta":"bad_id","file_url":"https://raikou1.donmai.us/d3/4e/d34e4cf0a437a5d65f8e82b7bcd02606.jpg","large_file_url":"https://raikou1.donmai.us/d3/4e/d34e4cf0a437a5d65f8e82b7bcd02606.jpg","preview_file_url":"https://raikou1.donmai.us/preview/d3/4e/d34e4cf0a437a5d65f8e82b7bcd02606.jpg"}

test('fetches', t => {
  return dataFetcher('https://danbooru.donmai.us', '/posts/1.json').then(data => {
    t.deepEqual(data, sample)
  })
})